apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zabbix-web2
  namespace: zabbixcluster
spec:
  ingressClassName: nginx
  rules:
  - host: zabbix.local
    http:
      paths:
      - path: /
        backend:
          serviceName: zabbix-web
          servicePort: 80
