apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbixweb1
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: zabbix.local
    http:
      paths:
      - path: /
        backend:
          serviceName: zabbix-web
          servicePort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbixweb2
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: zabbix.local
    http:
      paths:
      - path: /
        backend:
          serviceName: zabbix-web
          servicePort: 80
