apiVersion: v1
kind: Namespace
metadata:
  name: zabbixcluster

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zabbix-web2
  namespace: zabbixcluster
spec:
  ingressClassName: nginx
  rules:
  - host: zabbix.local
    http:
      paths:
      - path: /
        backend:
          serviceName: zabbix-web-svc
          servicePort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-svc
  namespace: zabbixcluster
  labels:
    app: zabbix
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: zabbix-web
---

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-svc
  namespace: zabbixcluster
  labels:
    name: zabbix-server
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    name: zabbix-server
---

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-db-svc
  namespace: zabbixcluster
  labels:
    app: zabbix
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: zabbix-db
  selector:
    name: zabbix-db
   
   
---


apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  namespace: zabbixcluster
  labels:
    app: zabbix-web
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: monitoringartist/zabbix-xxl:latest
          ports:
          - containerPort: 80
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password
          - name: ZS_DBHost
            value: zabbix-db-svc
          - name: ZW_ZBX_SERVER
            value: zabbix-server-svc
          - name: ZS_enabled
            value: "false"
          - name: ZA_enabled
            value: "false"
          - name: ZW_enabled
            value: "true"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-db
  namespace: zabbixcluster
  labels:
    app: zabbix-db
    tier: zabbix-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-db
        app: zabbix-db
        tier: zabbix-db
    spec:
      containers:
        - name: zabbix-db
          image: monitoringartist/zabbix-db-mariadb
          ports:
          - containerPort: 3306
            name: mariadb
          env:
          - name: MARIADB_USER
            value: zabbix
          - name: MARIADB_PASS
            value: my_password
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: zabbix-db-storage
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  namespace: zabbixcluster
  labels:
    app: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: monitoringartist/zabbix-xxl:latest
          ports:
          - containerPort: 162
            name: snmptrapd
          - containerPort: 10051
            name: zabbix-trapper
          - containerPort: 10052
            name: zabbix-jmx
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password
          - name: ZS_DBHost
            value: zabbix-db-svc
          - name: ZS_enabled
            value: "true"
          - name: ZA_enabled
            value: "true"
          - name: ZW_enabled
            value: "false"
          - name: SNMPTRAP_enabled
            value: "true"
