apiVersion: v1
kind: Namespace
metadata:
  name: zabbixcluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbixcluster
spec:
  selector:
    matchLabels:
      run: zabbix-web
  replicas: 2
  template:
    metadata:
      labels:
        run: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: monitoringartist/zabbix-xxl:latest
          ports:
          - containerPort: 80
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password
          - name: ZS_DBHost
            value: zabbix-db-svc
          - name: ZW_ZBX_SERVER
            value: zabbix-server-svc
          - name: ZS_enabled
            value: "false"
          - name: ZA_enabled
            value: "false"
          - name: ZW_enabled
            value: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  namespace: zabbixcluster
spec:
  selector:
    matchLabels:
      run: zabbix-db
  replicas: 1
  template:
    metadata:
      labels:
        run: zabbix-db
    spec:
      containers:
      - name: zabbix-web
        image: monitoringartist/zabbix-db-mariadb
          ports:
          - containerPort: 3306
            name: mariadb
          env:
          - name: MARIADB_USER
            value: zabbix
          - name: MARIADB_PASS
            value: my_password
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: zabbix-db-storage
        emptyDir:
          medium: Memory


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbixcluster
spec:
  selector:
    matchLabels:
      run: zabbix-server
  replicas: 1
  template:
    metadata:
      labels:
        run: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: monitoringartist/zabbix-xxl:latest
          ports:
          - containerPort: 162
            name: snmptrapd
          - containerPort: 10051
            name: zabbix-trapper
          - containerPort: 10052
            name: zabbix-jmx
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password
          - name: ZS_DBHost
            value: zabbix-db-svc
          - name: ZS_enabled
            value: "true"
          - name: ZA_enabled
            value: "true"
          - name: ZW_enabled
            value: "false"
          - name: SNMPTRAP_enabled
            value: "true"
